apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactlist-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactlist
  template:
    metadata:
      labels:
        app: contactlist
    spec:
      containers:
      - name: contactlist
        image: drsnaj/contactlist_backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: contactlist-backend-service
spec:
  selector:
    app: contactlist
  ports:
  - port: 5000
    targetPort: 5000
