apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactlist-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: contactlist-frontend
        image: drsnaj/contactlist_frontend:v2.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: contactlist-config
              key: contactlist-api

---
apiVersion: v1
kind: Service
metadata:
  name: contactlist-frontend-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100
